// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8wX6jIVlB9kv0EhaBeTK-FNy3cNuE9iA',
    appId: '1:444026607788:web:a84b4ce2368f90a898e709',
    messagingSenderId: '444026607788',
    projectId: 'chat-app-9978a',
    authDomain: 'chat-app-9978a.firebaseapp.com',
    storageBucket: 'chat-app-9978a.firebasestorage.app',
    measurementId: 'G-8CJF12BXHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTM2ron4SlnDRuEIPEGVv9KuhKnD0KSCI',
    appId: '1:444026607788:android:be14ea55b7c2a61e98e709',
    messagingSenderId: '444026607788',
    projectId: 'chat-app-9978a',
    storageBucket: 'chat-app-9978a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwIseAQI_hsxFG5JnpmNaCKYQzzG8KX7U',
    appId: '1:444026607788:ios:5b680b0c205574fb98e709',
    messagingSenderId: '444026607788',
    projectId: 'chat-app-9978a',
    storageBucket: 'chat-app-9978a.firebasestorage.app',
    iosBundleId: 'com.example.cheatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwIseAQI_hsxFG5JnpmNaCKYQzzG8KX7U',
    appId: '1:444026607788:ios:5b680b0c205574fb98e709',
    messagingSenderId: '444026607788',
    projectId: 'chat-app-9978a',
    storageBucket: 'chat-app-9978a.firebasestorage.app',
    iosBundleId: 'com.example.cheatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8wX6jIVlB9kv0EhaBeTK-FNy3cNuE9iA',
    appId: '1:444026607788:web:e010e0666c80830c98e709',
    messagingSenderId: '444026607788',
    projectId: 'chat-app-9978a',
    authDomain: 'chat-app-9978a.firebaseapp.com',
    storageBucket: 'chat-app-9978a.firebasestorage.app',
    measurementId: 'G-QM130P0FE6',
  );

}